# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_auto_20170331_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 22, 17, 55, 376254)),
        ),
    ]
